vcontainer-bbmask.inc: add python3-pexpect,-ptyprocess
For container-yocto-builder, the container is the "host" and so
we need the "Build Host Packages" equivalent in [1]. When
we are building with mc:container-aarch64,-x86-64 multiconfig
and the vcontainer distro, we need python3-pexpect and its
dependency python3-ptyprocess to fulfill
packagegroup-yocto-builder-extras. Otherwise we see a build-time
error like:

ERROR: Nothing RPROVIDES 'python3-pexpect' (but mc:container-aarch64:
.../meta-virtualization/recipes-core/packagegroups/packagegroup-yocto-builder.bb
RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'python3-pexpect' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-pexpect']
ERROR: Required build target 'packagegroup-yocto-builder' has no buildable providers.
Missing or unbuildable dependency chain was: ['packagegroup-yocto-builder', 'python3-pexpect']

Remove the layer-wide meta-python BBMASK and allow these
specific recipes.

Once meta-python is allowed, there was an error for
meta-oe/dynamic-layers/meta-python which we do not need for the
above recipes. It can be enabled in the future when needed.

[1] https://docs.yoctoproject.org/brief-yoctoprojectqs/index.html#build-host-packages
Signed-off-by: Tim Orling <tim.orling@konsulko.com>