wic: move wic/ to files/wic
ERROR:  OE-core's config sanity checker detected a potential misconfiguration.
    Either fix the cause of this error or at your own risk disable the checker (see sanity.conf).
    Following is the list of potential problems / advisories:
    wic/wks files at /.../build/meta-virtualization/wic need to be moved to files/wic within the layer to be found/used

Signed-off-by: Tim Orling <tim.orling@konsulko.com>